Dockerfile.build
Makefile
README-devel.md

Instead of modifying my Silverblue host to get the deps to build `bootupd` I did a quick container image. Since others may benefit from this as well I decided to do some quick `Makefile` updates and send it up to see if it would be helpful.
- Dockerfile.build: The container recipe used to make the build image
- `create-build-container`: Uses the container runtime to make a build container
- `build-in-container`: Executes make inside the build container
- `CONTAINER_RUNTIME`: Allows overriding what container runtime will be used

Allow building in a container

---

systemd/bootupd.service

One of the benefits of running as a systemd service is getting
simple declarative access to sandboxing/containerization.
Since bootupd should never touch `/home`, let's flip on that
flag.  Also add `MountFlags=slave` in preparation for support
for handling read-only default mounts for `/boot/efi` for example,
like what ostree does for `/sysroot`.

bootupd.service: Add ProtectHome=yes

---

Cargo.toml
Makefile
packaging/rust-bootupd.spec
src/bootupd.rs
systemd/bootupd.service
tests/kola/test-bootupd

A good way to look at what we need is something much like
systemd's `bootctl` except for shim/grub2.
It's not as nice for admins to explicitly type
`/usr/libexec/bootupd`, plus it intermixes options
with things they shouldn't use.
Split options into frontend (`/usr/bin/bootupctl`) and backend
(things invoked on the build side).  Install via hardlinks
and dispatch by default on `argv[0]`.

Expose binary in /usr/bin/bootupctl

---

ci/build-test.sh

The test naming convention changed in cosa, let's grab all
the bootupd tests anyways in case we add more.

ci: Fix test script

---

src/bootupd.rs
src/model.rs

We could handle this better, but let's at least start
tracking when an update was interrupted so we can print it.

Track when an update is interrupted and print it

---

src/bootupd.rs
src/ipc.rs
src/model.rs
tests/kola/test-bootupd

Move more update logic to client side
Similar to the previous move of `status`, return a structure
from the daemon and render it on the client.  This actually
moves more logic for updating to the client too; the IPC request
updates just one component, and the client iterates over all
installed components to update.
This way we also better return "partial" status.
---
Move formatting of status to client
The way we were just serializing a `String` from daemon → client
was rather...crude.  Instead have the daemon return a serialized
status object which we print on the client end.
---
Rework IPC to use generics
Prep for moving things like printing output to the client.

Client refactor

---

tests/kola/test-bootupd

Perhaps in the future we'll allow non-root status but
that's a lot more code complexity, no immediate need
for it.

tests: Validate that we can't run bootupd as non-root

---

.cci.jenkinsfile
src/bootupd.rs

I got confused and thought it was "arm" in rust but no it really
is `aarch64`, matching the Fedora naming.
Tested to work in a podman fedora:32 container image on
a RHEL8 host `4.18.0-193.14.3.el8_2.aarch64`.

Fix build on aarch64

---

src/bootupd.rs
src/cli/mod.rs
src/main.rs

This moves CLI parsing logic and sub-commands handling to its own
module, making full use of structopt for matching verbs to enum
variant and for dispatching to the relevant entrypoint.

cli: split handlers and runners for sub-commands

---

src/bootupd.rs

Might as well output information at build time.

generate-update-metadata: Print the result

---

src/bootupd.rs
tests/kola/test-bootupd

Further ensure admins don't accidentally try this until we've
tested it very heavily.

update: Require BOOTUPD_ACCEPT_PREVIEW in environment

---

src/filetree.rs

UEFI doesn't care about timestamps on binaries, there's no reason
for us to do so either.  Nothing was using this value.

filetree: Remove timestamp

---

src/efi.rs
src/model.rs

Using local timestamps is obviously broken; while our
build process will probably use UTC, relying on that is
wrong, and clients may not use UTC.
Noticed this while going to do some other work around
comparing `ContentMetadata`.
I did verify that RPM's `%{buildtime}` is UTC - the source
invokes `time(NULL)` and the value isn't interpreted
when printed.

Use UTC for serialized timestamp

---

src/bootupd.rs
src/efi.rs
src/model.rs
tests/kola/test-bootupd

There's no good reason to have version numbers be optional.
They're essential for human understanding of things.
We still use a timestamp around for total ordering.
Rework the model to more precisely keep track of "upgradable".

Make version number not optional

---

src/efi.rs
src/util.rs

After refactoring this method was lying around as `#[allow(dead_code)]`.
Previously we were trying to use Rust unit tests more but
now we favor the real kola tests.
Let's use it again to double-check we're operating on the
right thing.

efi: Do check ESP is FAT

---

src/bootupd.rs

I forsee people pasting the output of `bootupctl status` into
issues and bugs, so let's gather this one by default.

status: Also print the boot method

---

src/bootupd.rs
src/component.rs
src/efi.rs

- Don't need to serialize anymore
- Use `Default` since it's nicer

efi: Some minor cleanup

---

src/bootupd.rs
src/cli/mod.rs
src/component.rs
src/efi.rs
src/filetree.rs
tests/kola/test-bootupd

Let's add support for checking the on-disk state.  This helps
cross-check our implementation and is also useful for administrators
(ref `ostree fsck`, `rpm -V` etc).

Add a `validate` command

---

Cargo.toml
Makefile
packaging/rust-bootupd.spec
src/bootupd.rs
src/cli/bootupctl.rs
src/cli/bootupd.rs
src/cli/mod.rs
src/main.rs
systemd/bootupd.service
tests/kola/test-bootupd

This reworks the CLI options parser to branch the inner logic
to accommodate two entrypoints, `bootupd` and `bootupctl`, into
a single multicall binary.

cli: rework into a multicall binary

---

src/bootupd.rs
src/cli/bootupd.rs
src/daemon/mod.rs

This tweaks daemon core-logic to keep going on client-induced errors,
logging them at "error" level.
It also introduces docstrings and minor reflows to ease casual code navigation.
/cc @cgwalters

daemon: log and keep going on client errors

---

Cargo.lock
Cargo.toml
src/filetree.rs

An embarrassing bug where I accidentally intermixed
absolute path handling with fd-relative, and wasn't caught
by either the unit tests or integration tests because the
current directory was writable.
But it was caught by a new test suite which doesn't use
`rpm-ostree usroverlay`.

filetree: Fix creation of parent directories

---

src/filetree.rs

For a while the filetree code wasn't used by EFI, now it is
again, so remove most of the `allow(dead_code)` and only use
`cfg(test)` for a few of them that are only used by tests.
Came up in PR review.

filetree: Remove lots of #[allow(dead_code)]

---

src/cli/bootupctl.rs
src/cli/bootupd.rs
src/cli/mod.rs
src/main.rs
systemd/bootupd.service

This introduces a new `-v(vv)` flag separately on both `bootupd` and `bootupctl`
to control log verbosity. The default level only shows warnings and
higher priorities.
The service unit sets up the daemon to log info messages too, and
can be overridden via a drop-in.
This also introduces some basic unit-tests on CLI parsing.
/cc @cgwalters

cli: add flag to control logging level

---

src/cli/bootupd.rs
src/daemon/mod.rs
systemd/bootupd.service
tests/kola/test-bootupd

There's no reason to sit there taking up RAM just because
someone did `bootupctl status`.  Properly implementing
exit-on-idle really requires an event loop (e.g. `tokio`)
but that'd be a large change.
For now let's just exit when a client disconnects.  However,
this quickly broke the test suite which does a lot of
commands in a row.
Tweak the systemd unit to allow more restarts, and also
add a few strategic sleeps.
Closes: https://github.com/coreos/bootupd/issues/43

daemon: Exit when done processing requests

---

Cargo.lock
Cargo.toml
src/bootupd.rs
src/cli/bootupctl.rs
src/cli/bootupd.rs
src/daemon/mod.rs
src/main.rs

This removes the current library/binary crate split, leaving
only the application in place.
The original idea was to add the logic as a vendored library into
rpm-ostree for an emergency fix. However the urgency dropped and
this now lives as a self-standing application.
We may or may not consider re-adding it later on, but only for the
interop parts (paths, JSON, etc).
/cc @cgwalters

cargo: drop library crate, for now

---

src/model.rs
tests/fixtures/example-state-v0.json

I noticed we were missing `kebab-case` on a few structs (but
it doesn't matter since none of them have a name that would change).
To ensure we don't regress on parsing old file formats, add a JSON
file from a current system and test loading it.

state: Consistently kebab-case and validate a previous saved format

---

src/bootupd.rs
src/coreos.rs
src/main.rs
src/model.rs
tests/kola/test-bootupd

This is prep for work on "adoption":
https://github.com/coreos/bootupd/issues/38
In order to (as safely as possible) take over management
of a system *not installed via bootupd* we want to gather
as much information as we can.
For example, we can use the imgid as the "version" of the
current bootloader data.

Parse and print CoreOS aleph version

---

src/bootupd.rs

I was debugging a failure to write the statefile which
turned out to be me having
https://github.com/coreos/fedora-coreos-config/pull/659
locally.
Anyways let's add some error context to aid future debugging.

main: Add more error context

---

systemd/bootupd.service

Just on general principle.  In particular the combination
of a readonly `/usr` and `WorkingDirectory=/usr/share/empty`
will give us a consistent clean error if we somehow accidentally
write to the current working directory.

Use a lot more systemd hardening features

---

src/bootupd.rs
tests/kola/test-bootupd

If it's indented it looks like it's part of the EFI component.

status: Fix indentation of CoreOS aleph image ID

---

.cci.jenkinsfile

Jenkins doesn't seem to render nested stages, so drop the
outer one.  This makes CI look nicer and more useful
as we add more testing runs.

ci: Remove unnecessary outer stage{}

---

src/bootupd.rs
src/coreos.rs

Prep for adoption; we use the aleph as a `ContentMetadata`
which wants both a timestamp and a version string.

coreos: Add timestamp to aleph version

---

src/model.rs
tests/fixtures/example-status-v0.json

We do want tooling to parse `bootupctl status --json`, so let's
validate we're not unexpectedly breaking it.

model: Also validate serialized status

---

src/model.rs

This is a big hammer and eventually what we'll really need
to do is introduce versioning or compatibility flags.
That said, for now it's better to ensure we're not reading
anything unexpected.
And in a scenario where bootupd is downgraded, it's not
a really big deal because it just means you can't update
the bootloader - which you probably don't want to do
if you're downgrading the operating system anyways.

model: Deny unknown saved state fields

---

src/bootupd.rs
src/cli/bootupctl.rs
src/model.rs
tests/fixtures/example-status-v0.json

For now let's address concerns over how we represent
the operating system by dropping them from the status
JSON.  Instead detect CoreOS specifically client side
too and print the aleph there.

 Drop operating system from status, print client side

---

src/bootupd.rs
tests/e2e-adopt/e2e-adopt-in-vm.sh
tests/e2e-update/e2e-update-in-vm.sh
tests/kola/test-bootupd

I'm increasingly confident in our testing, so let's
drop the requirement to set the environment variable.

Drop requirement for BOOTUPD_ACCEPT_PREVIEW=1

---

src/backend/mod.rs
src/backend/statefile.rs
src/bootupd.rs
src/main.rs

This introduces a write-lock guard in order to to ensure that all
update operations attempted on the on-disk statefile have properly
acquired the system-wide lock first.
/cc @cgwalters

backend/statefile: add a write-lock guard for statefile updates

---

src/bootupd.rs
src/efi.rs

I think we're hitting issues in CI in this path right now.
See: https://github.com/coreos/fedora-coreos-config/pull/711.

Add some more error-prefixing

---

src/component.rs

I think this is the error we're seeing in
https://github.com/coreos/fedora-coreos-config/pull/711#issuecomment-716780537
But let's add some error prefixing to be sure for the future.

component: Add error prefixing

---

Cargo.lock
Cargo.toml
src/backend/statefile.rs

Less code, not as error prone (e.g. forgetting to `flush()` a `BufWriter`)
and technically better using `O_TMPFILE`.
(And for symmetry also use openat for reading in the same file case)

Use new openat-ext APIs for writing files

---

src/backend/statefile.rs
src/main.rs
src/model_legacy.rs
tests/fixtures/example-state-v0-legacy.json

Since bootupd 0.1.1 shipped in FCOS stable
we need to support updating it, as well as
"pre-bootupd" systems and bootupd 0.2 systems.
I tested this manually; not yet adding an e2e yet for
this because our test suite is already really
expensive and the unit test covers most of it.
Closes: https://github.com/coreos/bootupd/issues/91

Parse old "0.1" format installed state format

---

.github/workflows/rust.yml

This adds more jobs to the existing GH actions workflow, in order
to cover lintings (rustfmt and clippy), minimum toolchain (MSRV),
beta/nightly channels, and building in release mode.

gh/workflows: add jobs for linting, MSRV, release builds

---

.github/ISSUE_TEMPLATE/release-checklist.md
ci/prepare-release.sh

Taken from the one currently in coreos-installer:
https://github.com/coreos/coreos-installer/blob/master/.github/ISSUE_TEMPLATE/release-checklist.md
But tweaked in various ways:
- I want to continue to use `git-evtag`, will try to teach `cargo-release` about that at some point.
- Rework the vendoring stuff to be a script and run beforehand

Add a release-checklist + script

---

src/bootupd.rs
src/component.rs
src/efi.rs
src/model.rs
tests/e2e-adopt/e2e-adopt-in-vm.sh

Came up in review in https://github.com/coreos/fedora-coreos-docs/pull/203
Basically it's confusing to users that they need to understand
the difference between `update` and `adopt-and-update`.
From bootupd's perspective these are quite different things;
the first case is a completely known quantity, the second isn't.
However...we can be pretty confident that we can update systems
that have a CoreOS aleph version (i.e. they were generated by coreos-assembler),
since we haven't changed how the bootloader is installed there
really much at all.
This means that for now RHCOS 4.{1,2} bootimages that were
generated via Anaconda will still require `adopt-and-update`,
but detecting and validating that can come as a second phase.
The high level logic here is that the status gains a new
`confident: …

Update all {F,RH}CoreOS systems that have an aleph version

---

src/bootupd.rs
src/cli/bootupctl.rs
tests/e2e-update/e2e-update-in-vm.sh

This is a middle ground between:
1) Parse arbitrary text output from `bootupctl status`; this could
change at any time.
2) Parse JSON from `bootupctl status --json`; parsing this requires
knowlege of bootupd and the JSON format still isn't 100% fixed
in stone either.
Projects like https://github.com/openshift/machine-config-operator/
will basically want a flow that just allows them to check for
outstanding updates and apply them one node at a time.

Add bootupctl status --print-if-available

---

src/backend/statefile.rs
src/bootupd.rs
src/component.rs
src/efi.rs

In order to tackle https://github.com/coreos/bootupd/issues/108
we need to switch to not assuming `/` as the update source.
We do provide the system root as a string in some cases but
not all.  Let's go fd-relative.

Pass sysroot through updates

---

src/bootupd.rs
src/component.rs
src/efi.rs

More prep for https://github.com/coreos/bootupd/issues/108
Similar to the previous PR for updates.

Thread sysroot through adopt+update flow

---

src/bootupd.rs
src/component.rs
src/efi.rs

More incremental work on https://github.com/coreos/bootupd/issues/108
In some cases we're using both an absolute path and a dfd;
fixing that gets involved because we need to use it for child
processes too, which will require some more prep work.

Thread sysroot through update query flow

---

src/cli/bootupctl.rs

We need triple `///` to show in `bootupctl status --help`.

status: Fix docstrings

---

src/bootupd.rs
src/component.rs
src/efi.rs

More incremental work on https://github.com/coreos/bootupd/issues/108

Thread sysroot through install flow

---

src/bootupd.rs
src/efi.rs
src/util.rs
tests/kola/test-bootupd

Minor changes from https://github.com/coreos/bootupd/pull/116
Tested on [FCOS with /boot and /boot/efi mounted ro](https://github.com/coreos/fedora-coreos-config/pull/659).

Handle ro /boot

---

Cargo.lock
Cargo.toml

Mainly internal cleanups, plus support for a read-only `/boot`
and `/boot/efi`.

Release 0.2.4

---

Cargo.lock
Cargo.toml

This adds support for having the ESP not be mounted by
default, which we are going to do in Fedora CoreOS at least.

Release 0.2.5

---

doc/dependency_decisions.yml

https://lists.fedoraproject.org/archives/list/rust@lists.fedoraproject.org/thread/UE4FU27OAHXQ2EOV5OFSXGHELUWZYSJM/
discusses license compliance as something a downstream
distribution should be doing.  Yes.  But also, this is something
that *upstreams* should be doing as part of their CI.
Looking around I found https://github.com/pivotal/LicenseFinder
which looks decent; it handles multiple languages, has
a container image, is FOSS itself etc.
I ran through it for bootupd and this lists the approvals.
The next step here is to validate this in CI.

doc: Add license_finder permitted licenses

---

Cargo.lock
Cargo.toml
src/backend/statefile.rs
src/component.rs
src/ipc.rs

Effectively what we're doing here is creating a human-readable subset
of the stack trace.  This is nicer than having the calling functions
add `with_context()` because it's more verbose (gets duplicative at
each call site), easy to forget, etc.

Add and use fn-error-context for more reliable error traces

---

.dockerignore
ci/prow/Dockerfile
ci/prow/fcos-e2e.sh

Not actually testing what you think you are is the worst.
At some point I think I added the `cd $(mktemp -d)` but that loses our overrides.  I'm going to try soon to centralize this as [a multi-stage test](https://docs.ci.openshift.org/docs/architecture/step-registry/) probably.

prow: Fix overrides

---

.cci.jenkinsfile
ci/prow/Dockerfile

Attempt to update both CCI and Prow.
xref https://github.com/coreos/fedora-coreos-tracker/blob/master/docs/ci-and-builds.md

ci: Update to latest buildroot model

---

.github/workflows/rust.yml
src/bootupd.rs
src/cli/mod.rs
src/component.rs
src/efi.rs

workflows: bump toolchains; restrict repository access; fix build/lint warnings

---

.cci.jenkinsfile
tests/e2e-update/e2e-update.sh

Need to tweak this to auto-detect gold versus updates, or
probably better just synthesize an update.

 tests/e2e-update: Bump to f34 grub

---

Cargo.lock
Cargo.toml

Changes:
* tests/e2e-update: Bump to f34 grub
* workflows: bump toolchains; restrict repository access; fix build/lint warnings
* OWNERS: remove
* git: rename master branch to main
* ci: Update to latest buildroot model
* cargo: update all dependencies
* lockfile: general refresh, update all openssl crates

Release 0.2.6

---

.cci.jenkinsfile

We're downgrading to an old grub2 build that is broken, so
we can't actually boot uefi after doing our hacks.
The correct thing here is to change bootupd CI to generate
synthetic RPMs instead of downloading old builds.  Will do that
at some point...

ci: Don't run basic scenarios

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml

This reverts back `clap` from 3.x to 2.x.
In order to land the initial 3.x update I made a minimum toolchain bump which turned out to be incorrect.
As such, this also resets the minimum supported Rust version to its previous value.
Ref: https://github.com/coreos/bootupd/pull/263#issuecomment-1005110600

cargo: revert back to clap 2.34

---

.github/workflows/rust.yml
Cargo.toml
src/bootupd.rs

RHEL 8.6 has a new-enough Rust to allow this.  Also, clap 3.0 needs Rust 1.54.0.

Update to Rust 2021; bump MSRV to 1.56.0

---

src/cli/bootupctl.rs
src/cli/bootupd.rs

It was lost in the switch to clap 3.1.

cli: reinstate `--version` flag

---

.cci.jenkinsfile

Tell Git that the current directory is safe, even though it's not owned by the current user.
Fixes https://github.com/coreos/bootupd/issues/333.

ci: fix e2e-update test with current Git

---

Cargo.toml
ci/prepare-release.sh

To reduce the size of our vendor tarball, xref https://github.com/coreos/fedora-coreos-tracker/issues/1240

Add `package.metadata.vendor-filter`

---

Makefile
packaging/rust-bootupd.spec
tests/e2e-update/e2e-update-in-vm.sh
tests/kola/test-bootupd

The fact that we're a systemd unit is mostly an implementation detail so that we get a natural locking mechanism and can reuse systemd sandboxing.
If you have the software installed, we want the socket to be enabled.
Having to work through adding this into presets is just compounding pain for shipping it in multiple places.
Instead, install a static symlink.

Statically enable bootupd.socket

---

src/efi.rs
src/main.rs

This is an even better fix for https://github.com/coreos/bootupd/issues/367
Basically in coreos-assembler today we're already mounting the ESP, so let's just reuse that existing mount if it's present.  This is also what we want for other systems that pre-mount the ESP.
(At least for now - long term to support redundant ESPs we'll need
to fully own all of this, but that can come later)

efi: Reuse existing mountpoint if available

---

Cargo.lock
Cargo.toml

Mainly because bootc work depends on the new EFI handling.

Release 0.2.9

---

src/bios.rs
src/bootupd.rs
src/cli/bootupd.rs
src/component.rs
src/coreos.rs
src/efi.rs
src/filetree.rs
src/main.rs
src/ostreeutil.rs
src/sha512string.rs
src/util.rs

bootupd: Prepare bootupd update directory for both components
- Prepare bootupd update directory which will save component metadata
files for both components.
---
Add bios.rs and implement generate_update_metadata
- This will generate `/usr/lib/bootupd/updates/BIOS.json`, which will have the version and timestamp of `grub2-tools`
---
bios.rs: implement BIOS (grub) install function
- Add `--device </dev/vda>` option to install BIOS bootloader (grub)
- If call function without `--device`, will only install EFI.
---
bios.rs: add `run_update` to support bootupctl update
- This is the same action as `install`
---
bios.rs: return `Skipped` when run `bootupctl validate` for BIOS
---
ppc64: fix build warning
- The fix looks really ugly. Just realize bootupd is not supported on ppc yet, maybe we …

bios.rs: implement BIOS (grub)

---

xtask/Cargo.toml
xtask/src/main.rs

This is a copy of
https://github.com/containers/bootc/commit/0c8c6834f0aecdf18d8b9eec07a3810743ad0d37
I was hitting an issue with our COPR builds where we were getting *earlier* builds because the git hash was the first component of the version, and the leading numbers there don't increment, and RPM wants higher versions.
Force newer-is-better by injecting the date (up to the minute, not second because we're not going to build more than one a second).

xtask: Add timestamp to version

---

src/bios.rs

This fixes https://github.com/containers/bootc/issues/64
I didn't chase through what was going wrong in grub; there's a whole lot of layers here.  But for the CoreOS use case we know the modules we need, so we should specify them.

bios: Always add `part_gpt`

---

README.md

Came up re https://github.com/coreos/fedora-coreos-tracker/issues/1441

README.md: Update status to reflect current reality

---

.github/workflows/rust.yml
Cargo.toml
src/bios.rs
src/bootupd.rs
src/component.rs
src/efi.rs
src/filetree.rs
src/util.rs

Bump MSRV to 1.66.0
This is what we have elsewhere in coreos/ and I think will
be prep for further PRs.
---
Allow clippy::box_default
Because this code is right, and what `cargo clippy --fix` wants
to do actually breaks compilation.
---
tree-wide: Fix various minor clippy lints
The unnecessary borrows one always feels like the most churn
for the least value, but let's do it.
---
filetree: Use `.write_all()` in tests
This clippy lint catches a real bug.
---

Bump MSRV to 1.66.0

---

Cargo.lock
Cargo.toml
src/efi.rs

Skip adoption if systemd-boot or systemd-stub are used since `bootctl` will handle updating them. The 2nd commit is IMO correct but more controversial. I needed it to test that our sd-boot system would be detected and skipped. It did work in that case, though:
```
Apr 11 10:56:49 endless bootupd[3086]: [DEBUG bootupd::efi] Reusing existing "/boot"
Apr 11 10:56:49 endless bootupd[3086]: [TRACE bootupd::efi] No CoreOS aleph detected
Apr 11 10:56:49 endless bootupd[3086]: [TRACE bootupd::efi] Skipping adoption for "systemd-boot 251.2+dev56.9738984-22bem1"
```
I'm not that familiar with writing rust tests, but I think the UTF-16 string function could be written to take an optional root and then a test that writes various stuff into `<testroot>/sys/firmware/efi/efivars/<somevar>` could be …

Don't adopt systemd boot loaders

---

.github/dependabot.yml
.github/workflows/rust.yml

Created by [GitHub workflow](https://github.com/coreos/repo-templates/actions/workflows/sync.yml) ([source](https://github.com/coreos/repo-templates/blob/main/.github/workflows/sync.yml)).
Sync with coreos/repo-templates@2d36a16f87ae9ed96780ae778b3ce410d76025e4.

Sync repo templates ⚙

---

Cargo.lock
Cargo.toml

Bump rust-version = 1.70.0
It's what's in C9S and we can rely on that.
---
Release 0.2.10
---

Bump rust-version = 1.70.0 && Release 0.2.10

---

Cargo.lock
Cargo.toml
src/model_legacy.rs
src/util.rs
tests/e2e-update/e2e-update.sh

Since we got way behind and dependabot isn't going to catch up.

Cargo.lock: Mass update

---

src/filetree.rs

Tested in Fedora Silverblue 38 upgraded from 34 (upgrades from 36 isn't affected).
Fixes https://github.com/coreos/bootupd/issues/467.

Fix removal in non-existent files

---

Makefile
contrib/packaging/bootupd.spec
src/grub2/README.md
src/grub2/grub-static-efi.cfg
src/grub2/grub-static.cfg

Pull this from coreos-assembler; prep for moving ownership of it into bootupd.
In the short term, this will allow install tools to copy it manually.

Import static grub configuration

---

src/bootupd.rs
src/cli/bootupd.rs

So one can use e.g. `--component=EFI` to only install UEFI.

install: Add support for selecting components

---

.cci.jenkinsfile

Let's see if this unbreaks our CI.

ci: Test fast tracking virtiofsd

---

src/cli/bootupd.rs

As of right now all known callers of this pass `/`.  More generally we now expect bootupd to run in a container inside its target root; never outside of it.
xref https://github.com/coreos/coreos-assembler/pull/3631

backend: Make --generate-update-metadata require a sysroot of /

---

src/bios.rs
src/efi.rs
src/main.rs
src/packagesystem.rs
src/util.rs

Refactor rpm bits into packagesystem module
Prep for cleaning this up and making it more generic
to support non-rpm systems in a pluggable way.
---
De-duplicate package querying
There's no reason to have two separate functions here.
---
packagesystem: Add a unit test
On general principle.
---

Packagesystem cleanup

---

Makefile
src/bootupd.rs
src/cli/bootupd.rs
src/efi.rs
src/grub2/configs.d/README.md
src/grub2/grub-static-post.cfg
src/grub2/grub-static-pre.cfg
src/grubconfigs.rs
src/main.rs

grub: Support multiple platform files
In practice, just one should be enough but let's expand
in case.
---
Add support for installing static grub configs
Currently these are duplicated in osbuild and coreos-assembler.
We will aim to deduplicate them here.
Ideally we'd add support for "day 2" updates of these; I started
on a patch for that but it's sadly messy.
This is an incremental improvement.
---

 Add support for installing static grub configs

---

src/grub2/grub-static-pre.cfg

This was in the very first commit that added a GRUB config to cosa. If set, it causes GRUB to pause output if the screen is full of messages until the user presses a key.
That's just incompatible with automation, so nuke it. Any warnings from GRUB should end up in the serial console logs still.
One way this can happen is if booting from multipath. GRUB tries each path in turn until it can read from it. For each tried path that's non- optimized, it'll log a message. So if the device has a large enough number of paths, we can trigger the pager functionality and hang boot.
Probably fixes: https://issues.redhat.com/browse/OCPBUGS-20123

grub.cfg: drop `set pager=1`

---

contrib/packaging/bootupd.spec

No reason to have them be separate, that's what I ended up doing in Fedora.
(We should probably delete this spec file...)

packaging: Move static configs into main package

---

src/bootupd.rs
src/cli/bootupd.rs

This drains the code from
https://github.com/containers/bootc/pull/155/commits/20aa19ce6da58078999368e4f6dd948b2e3d990b
Because it will also be what Anaconda wants to do by default.

Add `backend install --auto`

---

src/bootupd.rs

Closes: https://github.com/coreos/bootupd/issues/550
I believe we don't have anything to do here; zipl always merges kernel/initramfs/bootloader and hence s390x updates are owned by ostree effectively.

No-op on s390x

---

src/grubconfigs.rs

I hit this when testing `bootc install` in a loop, it seems like we could be implicitly depending on this directory already having been created.

grubconfigs: Ensure grub2 dir exists

---

src/bios.rs
src/bootupd.rs
src/cli/bootupd.rs
src/component.rs
src/efi.rs
src/filesystem.rs
src/grub2/grub-static-efi.cfg
src/grubconfigs.rs
src/main.rs

In FCOS we never tried to support root=boot, but for bootupd
to do alongside installs in the general case we have to.
There were two things to fix here:
- Tweak the EFI "trampoline" to check for both $prefix/grub.cfg and $prefix/boot/grub.cfg
- Add support for writing the boot UUID into both places
(This avoids higher level tools like bootupd needing to know
about how to find the EFI vendor dir)
This more fully replicates the logic in coreos-installer.
---

Add support for root=boot (with EFI) and writing UUID file

---

tests/e2e-update/e2e-update.sh

Part of the every-6-months CI breakage.

ci: Adapt for Fedora 39

---

src/main.rs

The style lints are more annoying than useful as a general rule.

`allow(clippy::style)`

---

src/efi.rs
src/filesystem.rs

efi: Add more debugging for efibootmgr invocation
- Show what `bootcurrent` is
- Add the process exit status
---
filesystem: Copy stderr on failure
To aid debugging.
---
filesystem: Only capture needed columns
This fixes compatibility with current c9s `findmnt`, which otherwise
errors out with
`findmnt: ACTION column is requested, but --poll is not enabled`
---

two minor patches + c9s compat

---

src/grubconfigs.rs

We add the GRUB2DIR creation in ece9120 but there is an earlier use of that directory if there are dropins so let's move the creation of the directory earlier before the dropins are processed.
I hit this because I'm testing out things on FCOS. Building a qemu and metal image works just fine, because in that case we are doing the MBR install using `grub2-install` and I guess that tool creates the directory. In the metal4k case, though, there is no BIOS install and thus we get here and the GRUB2DIR doesn't exist and bootupd fails.

grubconfigs: move the GRUB2DIR creation earlier

---

src/bootupd.rs
src/coreos.rs
src/efi.rs
tests/kola/test-bootupd

In https://github.com/osbuild/osbuild/pull/1475 we are updating
aleph version to have more information and some of the fields
are changing slightly. Notably here `imgid` is no longer going to
be populated and `build` -> `version` now. Let's make these tweaks
and also just drop any fields from the definition here that we
aren't using to tolerate changes better.

coreos: update aleph version handling

---

Cargo.lock
Cargo.toml

Cargo.lock: Update *
Dependabot isn't keeping up.
---
Release 0.2.17
---

Release 0.2.17

---

.github/workflows/ci.yml
Makefile
ci/Containerfile.c9s

This helps effectively test e2e things like `--with-static-configs`.

ci: Add a workflow which does an install via bootc

---

.github/workflows/ci.yml
src/bootupd.rs
src/model.rs

Currently our static configs don't directly support updates. (They really should)
We also have a use case around simply introspecting the state that static configs were enabled (xref https://github.com/ostreedev/ostree/pull/3150) where we want to have ostree not run grub2-mkconfig in this case.
In preparation for both of these things, add tracking of our *own* version of the static configs into the metadata.
In theory of course, static configs could include other components (ignition, greenboot, etc.) and we should track those too.  For now this at least gets us basic metadata.

model: Add tracking of our own static config versions

---

Cargo.lock
Cargo.toml
src/model.rs

Xerf to https://github.com/chronotope/chrono/pull/1450

deps-update: bump chrono from 0.4.34 to 0.4.35

---

src/efi.rs
src/grubconfigs.rs

Fix https://github.com/coreos/bootupd/issues/630

grubconfig: handle efi vendordir better

---

src/efi.rs
src/grubconfigs.rs

Minor fix for https://github.com/coreos/bootupd/pull/633

aa64: Minor fix for efi vendordir

---

src/bootupd.rs
tests/e2e-update/e2e-update-in-vm.sh

Keep current format to avoid having to update Fedora CoreOS tests as well.
Based on: https://github.com/coreos/bootupd/pull/472
Co-authored-by: Colin Walters <walters@verbum.org>
Closes: https://github.com/coreos/bootupd/issues/445

Print previous version too when updating

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
src/bios.rs
src/bootupd.rs
src/component.rs
src/efi.rs
src/grubconfigs.rs

Add `get_efi_vendor` method to both the bios and efi backends.
See Colin's comment
https://github.com/coreos/bootupd/pull/646#issuecomment-2089226909
---
ci: add `bootc install to-disk` test in c9s-bootc-e2e

Add `get_efi_vendor` method to both the bios and efi backends

---

Cargo.lock
Cargo.toml
src/efi.rs

Copy Timothée's comment:
We want to be able to use `bootupd backend install --update-firmware`
in Anaconda to setup the boot order on EFI systems.
The issue is that when called with `--update-firmware`, bootupd
currently removes the `BootCurrent` boot entry, and then adds a
new BootEntry for the system being installed.
The current Anaconda behavior is to remove all boot entries that
match the product name, then create a new boot entry using the
product name and set it as the first one in the boot order.
To sync with Anaconda behavior, when called with `--update-firmware`,
bootupd will remove all boot entries that match the product name, 
using the same Anaconda definition 
`ANACONDA_PRODUCTNAME=$(sed -r -e 's/ *release.*//' /etc/system-release)`
from …

efi: change `--update-firmware` to match current Anaconda logic

---

contrib/packaging/bootupd.spec

Drop systemd service since https://github.com/coreos/bootupd/commit/261fb5e7f28b9bd2c6099fd2d484f158adffb221, so we do not need this. See error in ci log:
```
RPM build errors:
File not found: /builddir/build/BUILD/bootupd-xxx-build/BUILDROOT/usr/lib/systemd/system/*
```

bootupd.spec: remove `%{_unitdir}`

---

.github/workflows/ci.yml

See: https://github.com/ostreedev/ostree/pull/3270

github/workflows: Update to ubuntu-24.04 & podman

---

Cargo.lock
Cargo.toml
src/cli/bootupctl.rs
src/efi.rs
src/filesystem.rs
src/filetree.rs
src/util.rs

We already have rustix as a dependency; now that we don't use IPC anymore it's trivial to port to rustix. I prefer its API and maintainer.

Port to rustix, drop nix

---

.github/workflows/cross.yml

Because we have a lot of arch conditionals that would be easy to break.

ci: Add cross-arch builds

---

README.md

See: https://github.com/coreos/bootupd/pull/663

README: Update now that it is no longer a daemon

---

.cci.jenkinsfile
tests/e2e-update/e2e-update.sh

- Remove fast track for `virtiofsd` as higher version is installed
- Update `grub2` to newer version in ci testing

ci: minor updates

---

Cargo.lock
Cargo.toml
src/efi.rs

Read `/etc/system-release` if exists, else get `NAME` from `/etc/os-release`
See https://bugzilla.redhat.com/show_bug.cgi?id=2268505#c24

efi: sync bootentry label with Anaconda

---

Cargo.lock
Cargo.toml
src/efi.rs

Inspired by https://github.com/coreos/bootupd/pull/685#discussion_r1679742803

efi: avoid reading global state for `get_product_name()`

---

Cargo.lock
Cargo.toml
src/bootupd.rs
src/efi.rs
src/failpoints.rs
src/filetree.rs
src/main.rs
tests/e2e-update/e2e-update-in-vm.sh
tests/e2e-update/e2e-update.sh

See Timothée's comment https://github.com/coreos/bootupd/issues/454#issuecomment-2178227050
Reuse `TMP_PREFIX`, logic is like this:
- `cp -a fedora .btmp.fedora`
- We start with a copy to make sure to keep all other files
that we do not explicitly track in bootupd
- Update the content of `.btmp.fedora` with the new binaries
- Exchange `.btmp.fedora` -> `fedora`
- Remove now "old" `.btmp.fedora`
If we have a file not in a directory in `EFI`, then we can copy
it to `.btmp.foo` and then act on it and finally rename it. No
need to copy the entire `EFI`.
Additional info for the logic:
- for removals, copy to temp dir, remove file in temp dir; if 
have a file not in a directory, remove it directly
- for changes/additions, copy to temp dir, write files in temp 
dir; if have a file not in a …

efi: update the ESP by creating a tmpdir and RENAME_EXCHANGE

---

src/cli/bootupctl.rs

If for whatever reason a bootupd command fails, it will leave the
systemd service unit in a failed state and systemd will then refuse to
run a unit under the same name with `systemd-run` again until the
failure is cleared.
Thus systematically call `systemctl reset-failed` before calling
`systemd-run` to clear any potential failures from previous calls.
Do not check the return code of the systemctl command on purpose as it
may fail if the unit does not exists yet, i.e. if no bootupctl command
has been run yet.
Also ignore stdout/stderr to avoid showing unexpected errors messages to
users.
See: https://github.com/coreos/bootupd/issues/707
See: https://github.com/coreos/bootupd/pull/663

bootupctl: Clear failure status from previous runs

---

src/bios.rs
src/component.rs
src/efi.rs
tests/e2e-update/e2e-update-in-vm.sh

Fixes https://github.com/coreos/bootupd/issues/717

bios.rs: add `adopt-and-update`

---

src/bios.rs
src/bootupd.rs
src/efi.rs

- When booting with `BIOS` and no `ESP` device detected, skip `UEFI` checking
- When booting with `UEFI` and no `bios_boot` partition found, skip `BIOS` checking
Fixes https://github.com/coreos/bootupd/issues/717

Skip `UEFI` or `BIOS` on none hybrid partition layout

---

src/bios.rs
tests/fixtures/example-lsblk-output.json

zram, sr0 (CD/DVD) and LUKS devices generally don't use partitions, thus don't have a partition table and thus don't have a partition table type so this field may be null.
Fixes: https://github.com/coreos/bootupd/issues/739

bios: Handle empty pttype from lsblk output

---

Cargo.lock
Cargo.toml

This is to include https://github.com/coreos/bootupd/pull/740.

Release 0.2.24

---

src/grub2/grub-static-pre.cfg

- grub.cfg was removed from the main branch in https://github.com/coreos/coreos-assembler/pull/3900
- Updated the link to maintain reference to the file’s origin and history.

grub-static-pre.cfg: Update link to preserve coreos-assembler history

---

src/coreos.rs
src/filetree.rs

Creation time will only be supported on the musl target once https://github.com/rust-lang/rust/pull/125692 lands.
This MR disables the tests that require creation time for musl.

Disable tests that require creation time on musl

---

src/filetree.rs
tests/e2e-update/e2e-update-in-vm.sh

Fixes https://github.com/coreos/bootupd/issues/762

filetree: skip the error if removing unexisting files

---

src/bootupd.rs

When we were reworking `bootc install` to try to run outside of a container, we hit on the fact that this query required rpm in the *host* context which is conceptually broken.
As part of severing our dependency on rpm (and package systems) in general let's just use our own crate version which we know at compile time.

main: Don't use package system to query our own version

---

src/ostreeutil.rs
src/packagesystem.rs

We don't need this on modern Fedora anymore for example. If we detect the sysimage path, then just use it.

Don't hardcode usr/share/rpm

---

.github/workflows/ci.yml
src/cli/bootupctl.rs
src/util.rs

The output in container is like:
```
bash-5.2# bootupctl status
Available: BIOS EFI
```
Fixes: https://github.com/coreos/bootupd/issues/788

status: support running in a container

---

.github/workflows/ci.yml
src/cli/bootupctl.rs

The output like:
```
bash-5.2# bootupctl status --json
{"components":["BIOS","EFI"]}
```
Fixes: https://github.com/coreos/bootupd/issues/794

status: support `bootupctl status --json` in container

---

src/efi.rs

Just like what we do with `/boot`.

efi.rs: ensure writable ESP mount

---

src/bootupd.rs
src/filetree.rs

```
warning: unnecessary use of `get(k).is_some()`
--> src/filetree.rs:187:34
|
187 |                 if self.children.get(k).is_some() {
|                                  ^^^^^^^^^^^^^^^^ help: replace it with: `contains_key(k)`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_get_then_check
= note: `#[warn(clippy::unnecessary_get_then_check)]` on by default
```

src: Fix 'contains_key' clippy lints

---

Cargo.lock
Cargo.toml
contrib/packaging/bootloader-update.service
src/backend/statefile.rs
src/cli/bootupctl.rs

Since our updates are non-transactional in general, we should at least be robust against some concurrent invocation of e.g. `reboot`.
Replaces: https://github.com/coreos/bootupd/pull/811

Catch and ignore SIGTERM during update operations

---

Cargo.lock
Cargo.toml
src/efi.rs
src/filesystem.rs
src/filetree.rs

This enables more code sharing. I didn't do a full port here, but this starts the ball rolling. In particular I think `run_and_parse_json()` is nice and elegant.

Use bootc-utils for command helpers

---

.github/ISSUE_TEMPLATE/release-checklist.md
ci/prepare-release.sh

Update vendor format to `tar.zstd`, see
[specific](https://src.fedoraproject.org/rpms/rust-bootupd/blob/rawhide/f/rust-bootupd.spec#_13)

ci: fix vendor format to `tar.zstd`

---

src/bootupd.rs
src/cli/bootupctl.rs

migrate-static-grub-config: Add GRUB static migration subcommand
Add a hidden subcommand that migrates existing systems using a dynamic
GRUB config to a static one.
This command is expected to be run after a successful bootloader update.
One way to do that is to add it as a droppin unit config for the
`bootloader-update.service` unit included in this repo:
```
$ cat /usr/lib/systemd/system/bootloader-update.service.d/migrate-static-grub-config.conf
[Service]
ExecStart=/usr/bin/bootupctl migrate-static-grub-config
```
This will be used on Atomic Desktops & IoT systems to migrate systems to
a static GRUB config before enabling composefs as GRUB curently does not
interact well with it [1].
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2308594
See: …

Import GRUB static migration code

---

Cargo.lock
Cargo.toml
src/bios.rs
src/blockdev.rs
src/main.rs

Prep for https://github.com/coreos/bootupd/issues/132
---
Add `bootc-blockdev` and local crate `blockdev`
See https://github.com/containers/bootc/pull/1050 & https://github.com/coreos/bootupd/pull/820#discussion_r1922629422
---
blockdev.rs: Add `#[allow(dead_code)]` for the unused functions
---
bios.rs: update functions to use blockdev

Add `bootc-blockdev` and local mod `blockdev`

---

.github/workflows/cross.yml
Cargo.toml

Fixes a warning when preparing the release.
---
Will also serve as a test for the failure in https://github.com/coreos/bootupd/pull/834

Cargo.toml: Add homepage

---

.github/workflows/ci.yml
.github/workflows/cross.yml

github/workflows: Run full CI for aarch64
- Install podman on aarch64 runners
- Only check for EFI on aarch64
- Update shim path for aarch64

github/workflows: Run full CI for aarch64

---

src/ostreeutil.rs

This was another debugging thing that got accidentally committed.

rpm_cmd: Also drop debugging `ls`

---

contrib/packaging/bootupd.spec
xtask/Cargo.toml
xtask/src/main.rs

xtask: Fix deprecated `default_features`
cargo warns about this.
---
xtask: Sync with bootc
In particular now that we have a `git` dependency, this turns
out to reveal some deficiencies in how e.g. the Fedora RPM
vendoring support works.
Sync the code from https://github.com/containers/bootc/pull/1068/commits/58fa21e54fa6868d5a266072b822454536398ef9
---
contrib/rpm: Sync vendor config from bootc
---
contrib/rpm: Two more fixes
- Use `rust-%{crate}` for name because that's what Fedora
does; the previous spec file sync was just broken
- Use a source archive generated from git, not a `.crate`; we
will stop publishing to crates.io.
Signed-off-by: Colin Walters <walters@verbum.org>
---

Rework vendoring

---

Cargo.lock
Cargo.toml
src/bios.rs

And automatically find the PReP partition.
Closes: https://github.com/coreos/bootupd/issues/837

bios+ppc64le: Support being passed a whole device

---

Cargo.lock
Cargo.toml

Cargo.lock: Mass update
Unfortunately our dependabot isn't keeping up.
---
Release 0.2.27
Signed-off-by: Colin Walters <walters@verbum.org>
---

Release 0.2.27

---

contrib/packaging/bootupd.spec

pairs with: https://gitlab.com/redhat/centos-stream/rpms/rust-bootupd/-/merge_requests/24

contrib/packaging/bootupd.spec: keep ix86 for c9s

---

xtask/src/main.rs

Fix:
```
$ git archive --format=tar --prefix=bootupd-0.2.27.49.g78dc8d3/ -o target/bootupd-0.2.27.49.g78dc8d3.tar HEAD
fatal: could not open 'target/bootupd-0.2.27.49.g78dc8d3.tar' for writing: No such file or directory
error: Packaging: command exited with non-zero code `git archive --format=tar --prefix=bootupd-0.2.27.49.g78dc8d3/ -o target/bootupd-0.2.27.49.g78dc8d3.tar HEAD`: 128
make: *** [/mnt/workdir-x9znfd3k/bootupd/.copr/Makefile:6: srpm] Error 1
```

xtask: create target dir before make srpm

---

README.md
src/bootupd.rs
src/component.rs
src/efi.rs
src/filetree.rs
src/main.rs
src/ostreeutil.rs

Allows update EFI bootloader on riscv64 similar to aarch64 and x86_64.
xref: https://github.com/coreos/fedora-coreos-tracker/issues/1931

support riscv64

---

tests/e2e-update/e2e-update.sh

I feel like this was a bit heavyweight for what we were gaining
from it since we were only modifying one file.
It just so happens also that the `git clone` was not including the
git submodule that we're now using in FCOS for bootc.
Let's just drop the "forking" and do something a bit more lightweight.

tests/e2e-update: drop manifest_fork logic; update to f42 grub RPMs

---

src/bootupd.rs

Add `struct RootContext` to gather the context up
Get pointer by https://github.com/coreos/bootupd/pull/923#issuecomment-2873134953
---
update: pass `RootContext` as parameter
Also remove duplicated sysroot as `openat::Dir::open("/")`

Add `struct RootContext` with devices

---

src/efi.rs

This is not to fix the issue, add context to print more info for
https://github.com/coreos/bootupd/issues/915
For example:
`error: generating metadata failed: Opening /usr/lib/bootupd/
updates/EFI: No such file or directory (os error 2)`

efi: add `context` when openning directory

---

.github/workflows/cross.yml
Cargo.toml

Simlar to https://github.com/coreos/coreos-installer/commit/948e9367b5401516fddfe73056662091b7471b00
update rust lint_toolchain to 1.84.1 in https://github.com/coreos/bootupd/pull/894

Cargo.toml: bump MSRV to 1.84.1

---

.cci.jenkinsfile
.github/workflows/rust.yml
src/grubconfigs.rs

Fixes https://github.com/coreos/bootupd/issues/746

grubconfig: create `boot/grub2/grubenv` if not existing

---

src/bios.rs
src/blockdev.rs
src/bootupd.rs
src/component.rs
src/efi.rs

This is the preparation for https://github.com/coreos/bootupd/pull/855.
The main target for this PR is: "efi: rewrite `ensure_mounted_esp()`", but find there are much to update consequently.
---
efi: rewrite `ensure_mounted_esp()`
Split into 2 parts:
- `get_mounted_esp()` to get mounted point esp
- `mount_esp_device()` to mount the passed esp device, return
the mount point
Then in `ensure_mounted_esp()` call the above 2 functions:
firstly check if esp is already mounted, if not, mount the passed
esp device.
---
efi: update `install()` and `update()` according to split change
---
adopt_update: pass `RootContext` as parameter
---
efi: update `validate()` according to the split change

efi: rewrite `ensure_mounted_esp()`

---

src/backend/statefile.rs
src/bootupd.rs
src/filetree.rs
src/freezethaw.rs
src/grubconfigs.rs
src/main.rs
src/util.rs

I went with a simple implementation of `fsfreeze_thaw_cycle()` compared to the ostree one as we are already protected from SIGTERM, and in case FIFREEZE is slow / stuck, there is no indication calling FITHAW will help, so l prefer to keep it simple.
I can move [grubconfigs: cleanup install()](https://github.com/coreos/bootupd/commit/432d56e48bfc3c380d88804a6127007a45e90e0f) to another PR but it need to be merged first

Add fsfreeze_thaw_cycle() + small cleanups

---

Cargo.lock
Cargo.toml

This release introduces five notable changes:
- Allows update EFI bootloader on `riscv64` similar to `aarch64` and `x86_64`. (https://github.com/coreos/bootupd/pull/916)
- Rework `grub2` default static config (https://github.com/coreos/bootupd/pull/841), that includes:
- Add support for `GRUB2_PASSWORD` in user.cfg (partially fix https://issues.redhat.com/browse/RHEL-78299)
- Include dropins instead of sourcing them, this should help updating config in the future
- Add multiple small dropins to match classic grub2 installs
- Add a simple implementation of `fsfreeze_thaw_cycle()`, that always call `syncfs()` first, then calls `ioctl(FIFREEZE)` and `ioctl(FITHAW)`. This function ensures filesystem state is fully flushed — especially for XFS. (https://github.com/coreos/bootupd/pull/948)
- …

Release 0.2.28

---

.github/workflows/ci.yml
src/grubconfigs.rs

Copy Colin's comment:
```
One overall issue on this is because we don't have a mechanism to
update the static configs, existing systems will stay as is.
```
See https://github.com/coreos/bootupd/issues/952 &
https://redhat-internal.slack.com/archives/C01BSEK9PM1/p1750152540290679

grubconfig: set `/boot/grub2/grub.cfg` file mode to `0600`

---

Cargo.lock
Cargo.toml
src/bios.rs
src/blockdev.rs
src/efi.rs
src/filesystem.rs
src/filetree.rs
src/grubconfigs.rs

For now we'll continue to publish bootupd as a crate,
but I think we should eventually stop doing this.
Closes: https://github.com/coreos/bootupd/issues/964

Use published bootc-internal-{utils,blockdev} crates

---

src/bios.rs
src/efi.rs

This is required when we use XFS, but it doesn't hurt to always use fsfreeze_thaw_cycle.

bios/efi: always use fsfreeze_thaw_cycle

---

Cargo.lock
Cargo.toml
src/bootupd.rs
src/model.rs
src/packagesystem.rs

Use `rpm::Evr` crate to parse and compare `version` when checking for update.
Inspired by Timothee's pointer:
https://github.com/coreos/bootupd/pull/938#issuecomment-3118960479
Fixes: https://github.com/coreos/bootupd/issues/933
Additional info:
Use rpm `0.16` instead of `0.17` as 1.84 does not support
feature `edition2024` that is requried by 0.17:
```
error: failed to parse manifest at `/root/.cargo/registry/src/
index.crates.io-6f17d22bba15001f/rpm-0.17.0/Cargo.toml`
Caused by:
feature `edition2024` is required
The package requires the Cargo feature called `edition2024`,
but that feature is not stabilized in this version of Cargo
(1.84.1 (66221abde 2024-11-19)).
```

package: move to compare `version` instead of `timestamp`

---

Dockerfile
src/bios.rs
src/bootupd.rs
src/component.rs
src/efi.rs

Prepare for step2 (in https://github.com/coreos/bootupd/issues/926) to install efi files from `usr/lib/efi`

efi: Extend `get_efi_vendor()` to support `usr/lib/efi`

---

Cargo.lock
Cargo.toml
src/blockdev.rs
src/bootupd.rs
src/component.rs
src/efi.rs
src/model.rs
src/model_legacy.rs
src/packagesystem.rs
tests/fixtures/example-state-versions-v0.json
tests/kola/test-bootupd
tests/tests/move-content-to-usr.sh

packagesystem: add struct `Module` about package name and evr
Also add `uapi_version::Version` to parse versions according to
Colin's comment https://github.com/coreos/bootupd/pull/983#discussion_r2284399377
---
Add `versions` to `ContentMetadata`
Inspired by Colin's comment https://github.com/coreos/bootupd/pull/977#discussion_r2278838151
We need `versions` to save struct like:
```
"versions": [
{"name": "pkg1", "rpm-evr": "1.0"},
{"name": "pkg2", "rpm-evr": "2.0"}
]
```
Then we read and compare versions, do not need to parse the
version in str format.
Co-worked by walters@verbum.org

Add `versions` to `ContentMetadata`

---

src/blockdev.rs
src/efi.rs

efi: Check shim exists and return earlier if not found
---
efi: Get the correct esp on multipath
Get pointer from Colin:
```
what we need to do here instead is "peel" through the multipath 
to find the block device(s) backing it, and then pick one of those.
```
When I do testing using mpath or backing device, find the 
results are the same, so I use mpath instead.
As there is no partition attribute on multipath env, this leads
error when install on multipath.
Fixes: https://issues.redhat.com/browse/RHEL-81039

efi: Get the correct esp on multipath when install
