coreos/bootupd

README.md
=> README.md: Various updates

src/bootupd.rs, src/component.rs, src/efi.rs, src/filetree.rs, src/sha512string.rs, tests/kola/test-bootupd
The test suite now passes again and has somewhat basic reasonable
coverage.
=> Fix update, clippy warnings, and start passing test suite

.cci.jenkinsfile, OWNERS
Prep for adding this to OpenShift Prow and CoreOS CI.
=> Add some CI infrastructure

src/sha512string.rs
=> sha512string: Add a test

src/bootupd.rs
Will try to add this to CI at some point.
=> main: Fix a clippy warning

.cci.jenkinsfile
This currently should just run only our test, we can't really
break anything else.
=> ci: Enable fcos build + kola

README.md
Help explain the rationale for this project's existence and future.
=> README.md: Explain more about relationship with rpm-ostree

.cci.jenkinsfile
=> ci: Use main fedora-coreos-config repo

src/efi.rs
I hit an error here and wanted to know which specific phase
was failing.
=> efi: Add more error context

src/daemon/mod.rs
This converts all daemon logic to stop directly printing to stdout/stderr,
and instead perform logging at the appropriate level.
/cc @cgwalters
=> daemon: avoid direct printing, log instead

tests/e2e/e2e-in-vm.sh, tests/e2e/e2e.sh, tests/kola/data/libtest.sh
With new content.  This helps test things more.
=> tests/e2e: Validate adding a new RPM

src/component.rs
On general principle but also prep for adding a new method.
=> component: Add a lot of docstrings

src/filetree.rs
=> filetree: Remove TODO and link to fcos umask PR

src/bootupd.rs
No tests yet, this will be covered in future "adoption" work.
=> status: Print message if nothing is installed

src/daemon/mod.rs
The requests aren't large, let's log the whole thing consistently
rather than having a copy/paste version for each request.  This
way we include the component too.
=> daemon: Log all requests at debug level

src/bootupd.rs
Prep for adoption work.
Previously we just bailed out if nothing was installed,
but we want to return a status even if there are no
components installed.
Rework the component list to be a map so we can conveniently
look up things by name.
=> main: Gather status even if no components are installed

src/cli/mod.rs, src/efi.rs, src/filetree.rs, src/model.rs
Nothing really important, may try to add clippy to CI at some point.
=> Fix clippy lints

src/bootupd.rs
Noticed in code review in another case.
=> main: Use unwrap_or_default()

src/backend/statefile.rs, src/bootupd.rs
Have the guard actually own the sysroot - matching how in
Rust the `Mutex<T>` type wraps what it guards.
Also add an `unlocked()` method to deal with the install case,
since there's no `/run` in the target root.
xref https://github.com/coreos/bootupd/pull/86#issuecomment-715351465
xref https://github.com/coreos/bootupd/pull/84#issuecomment-709414840
=> Rework sysroot/statefile locking

Cargo.lock, Cargo.toml, src/component.rs
Clean up this code to use the openat helpers too, just on
general principle of using fd-relative in more places.
=> component: More porting to openat

src/backend/statefile.rs, src/efi.rs
=> Fix two minor clippy bits

tests/fixtures/example-status-v0.json
Pointed out in code review in https://github.com/coreos/bootupd/pull/104
=> tests: Add a serialization test for adoptable data

README.md
And discuss the relationship with ostree specifically
around transactionality.
=> README.md: Add a question/answer section

src/filetree.rs
This updates file copying to use the newer `copy_file_at` from
openat-ext.
=> filetree: minor cleanup, use copy_file_at

OWNERS
Prow is not managing merges on this repo.
=> OWNERS: remove

Cargo.lock, Cargo.toml, src/cli/bootupctl.rs, src/cli/bootupd.rs, src/cli/mod.rs, src/main.rs
structopt has been merged into clap.
=> Replace structopt with clap 3.1

src/filetree.rs, src/util.rs
=> Use inline `format!` in a few places

src/efi.rs
This way we'll avoid leaking the mount in non-systemd cases.
Closes: https://github.com/coreos/bootupd/issues/367
=> efi: Unmount partition on drop

src/efi.rs
This finds the ESP as created by Anaconda based systems, and adds support for a working `bootupctl adopt-and-update`.
Closes: https://github.com/coreos/bootupd/issues/378
=> Add support for Anaconda-based installs

README-devel.md
Since e.g. we still need to do the second phase for Anaconda based systems.
=> doc: Add docs about distribution/OS integration

Cargo.lock, Cargo.toml
Mainly to get the Anaconda-based handling out.
=> Release 0.28

README.md
Motivated by discussion on fedora-devel-list.
=> README.md: We're not really a daemon

tests/e2e-update/e2e-update.sh
=> ci: Use f37 for overrides

src/efi.rs, src/util.rs
- Move code to func `parse_rpm_metadata` to parse the output of `rpm -q`
- Move code to func `rpm_query` to query rpm database, list the package and build times
=> util.rs: move some code to function to reuse

Cargo.lock, Cargo.toml
Obsoletes https://github.com/coreos/bootupd/pull/406
=> Update env_logger to 0.10

src/bootupd.rs, src/efi.rs
I was trying to debug something and these were helpful.
=> Add a few more debug log messages

src/efi.rs
=> efi: Only try to update firmware if booted via EFI

Cargo.lock, Cargo.toml
=> Release 0.2.19

Cargo.lock, Cargo.toml
Fixes https://github.com/coreos/bootupd/issues/682
=> Release 0.2.20

Cargo.lock, Cargo.toml
See https://github.com/coreos/bootupd/issues/712
=> Release 0.2.21

Cargo.lock, Cargo.toml
See https://github.com/coreos/bootupd/issues/727
=> Release 0.2.22

src/bios.rs, src/bootupd.rs, src/efi.rs, src/filetree.rs, src/util.rs
Convert to [let else](https://doc.rust-lang.org/rust-by-example/flow_control/let_else.html) where possible.
Inspired by https://github.com/coreos/bootupd/pull/723#discussion_r1757480310
=> Convert to `let-else` syntax

Cargo.lock, Cargo.toml
See https://github.com/coreos/bootupd/issues/733
=> Release 0.2.23

.github/workflows/cross.yml
See https://github.com/uraimo/run-on-arch-action/issues/155
=> ci: update `uraimo/run-on-arch-action` to v2 latest version

Cargo.lock, Cargo.toml
See https://github.com/coreos/bootupd/issues/779
=> Release v0.2.25

src/bios.rs
Fixes https://github.com/coreos/bootupd/issues/787
=> bios.rs: detect when payload is missing `grub2-modules`

src/bios.rs
=> bios.rs: pass --nofsroot to findmnt

Cargo.lock, Cargo.toml
Nothing huge here, but we want to keep up regular releases in general. I specifically want the fix for dropping the RPM dep.
=> Release 0.2.26

contrib/packaging/bootupd.spec
=> contrib/spec: Add BR on git

contrib/packaging/bootupd.spec
See: https://discussion.fedoraproject.org/t/f42-change-proposal-switch-to-git-core-self-contained/138975
=> contrib/packaging/spec: Use git-core instead of full git

src/filetree.rs
When doing removals, usually copy direcory to temp direcoty, then
do operations in temp dir, but should check if the dir is existed
in dest ESP.
Fixes https://github.com/coreos/bootupd/issues/856
=> update: do not try to copy a dir in the ESP if it does not exists

src/efi.rs
See https://github.com/coreos/bootupd/issues/690#issuecomment-2767840375
=> efi: remove trailing whitespaces to get correct product name

src/bootupd.rs, src/ostreeutil.rs
Add `fn get_ostree_bootloader()` to get `sysroot.bootloader` in ostree repo config.
Add `fn set_ostree_bootloader(bootloader: &str)` to set `sysroot.bootloader` value in ostree repo config.
Inspired by https://github.com/coreos/bootupd/pull/945#discussion_r2135764211
=> migrate: separate ostree command to functions

.cci.jenkinsfile, Cargo.lock, Cargo.toml
See https://github.com/coreos/bootupd/issues/981
=> Release v0.2.29

.github/ISSUE_TEMPLATE/release-checklist.md
See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository
=> Add template YAML frontmatter

src/bios.rs, src/bootupd.rs, src/component.rs, src/efi.rs
This follows https://github.com/coreos/bootupd/pull/991#discussion_r2320110879
=> Improve `get_efi_vendor()` to use `Path`

Cargo.lock, Cargo.toml
See https://github.com/coreos/bootupd/issues/1008
=> Release 0.2.31
